export interface Language {
  code3: string;
  code2: string;
  name: string;
  local: string;
}

export enum AppLanguage {
  en = "en",
  an = "an",
  ast = "ast",
  ca = "ca",
  cy = "cy",
  da = "da",
  de = "de",
  el = "el",
  en_GB = "en-GB",
  eo = "eo",
  es = "es",
  eu = "eu",
  fi = "fi",
  fr = "fr",
  ga = "ga",
  gd = "gd",
  gl = "gl",
  hi = "hi",
  hu = "hu",
  ia = "ia",
  id = "id",
  it = "it",
  ja = "ja",
  km = "km",
  ko = "ko",
  ne = "ne",
  nl = "nl",
  pl = "pl",
  pt_BR = "pt-BR",
  ro = "ro",
  ru = "ru",
  sv = "sv",
  th = "th",
  tr = "tr",
  uk = "uk",
  vi = "vi",
  zh_CN = "zh-Hans-CN",
  zh_HK = "zh-Hant-HK",
  zh_TW = "zh-Hant-TW",
}

interface AppLanguageConfig {
  code2: AppLanguage;
  name: string;
}

export const APP_LANGUAGES: AppLanguageConfig[] = [
  { code2: AppLanguage.en, name: "English" },
  // { code2: AppLanguage.an, name: "Aragonés – Aragonese" },
  // { code2: AppLanguage.ast, name: "Asturianu – Asturian" },
  // { code2: AppLanguage.ca, name: "Català – Catalan" },
  // { code2: AppLanguage.cy, name: "Cymraeg – Welsh" },
  // { code2: AppLanguage.da, name: "Dansk – Danish" },
  // { code2: AppLanguage.de, name: "Deutsch – German" },
  // { code2: AppLanguage.el, name: "Ελληνικά – Greek" },
  // { code2: AppLanguage.en_GB, name: "English (UK)" },
  // { code2: AppLanguage.eo, name: "Esperanto" },
  // { code2: AppLanguage.es, name: "Español – Spanish" },
  // { code2: AppLanguage.eu, name: "Euskera – Basque" },
  // { code2: AppLanguage.fi, name: "Suomi – Finnish" },
  // { code2: AppLanguage.fr, name: "Français – French" },
  // { code2: AppLanguage.ga, name: "Gaeilge – Irish" },
  // { code2: AppLanguage.gd, name: "Gàidhlig – Scottish Gaelic" },
  // { code2: AppLanguage.gl, name: "Galego – Galician" },
  // { code2: AppLanguage.hi, name: "हिंदी – Hindi" },
  // { code2: AppLanguage.hu, name: "magyar – Hungarian" },
  // { code2: AppLanguage.ia, name: "Interlingua" },
  // { code2: AppLanguage.id, name: "Bahasa Indonesia – Indonesian" },
  // { code2: AppLanguage.it, name: "Italiano – Italian" },
  // { code2: AppLanguage.ja, name: "日本語 – Japanese" },
  // { code2: AppLanguage.km, name: "ភាសាខ្មែរ – Khmer" },
  // { code2: AppLanguage.ko, name: "한국어 – Korean" },
  // { code2: AppLanguage.ne, name: "नेपाली – Nepali" },
  // { code2: AppLanguage.nl, name: "Nederlands – Dutch" },
  // { code2: AppLanguage.pl, name: "Polski – Polish" },
  // { code2: AppLanguage.pt_BR, name: "Português (BR) – Portuguese (BR)" },
  // { code2: AppLanguage.ro, name: "Română – Romanian" },
  // { code2: AppLanguage.ru, name: "Русский – Russian" },
  // { code2: AppLanguage.sv, name: "Svenska – Swedish" },
  // { code2: AppLanguage.th, name: "ภาษาไทย – Thai" },
  // { code2: AppLanguage.tr, name: "Türkçe – Turkish" },
  // { code2: AppLanguage.uk, name: "Українська – Ukrainian" },
  { code2: AppLanguage.vi, name: "Tiếng Việt – Vietnamese" },
  // { code2: AppLanguage.zh_CN, name: "简体中文 – Simplified Chinese" },
  // { code2: AppLanguage.zh_TW, name: "繁體中文 – Traditional Chinese" },
  // { code2: AppLanguage.zh_HK, name: "粵文 – Cantonese" },
];

export const LANGUAGES: Language[] = [
  // { code3: "aar", code2: "aa", name: "Afar", local: "Afaraf" },
  // { code3: "abk", code2: "ab", name: "Abkhazian", local: "Аҧсуа" },
  // { code3: "ace", code2: "", name: "Achinese", local: "Bahsa Acèh" },
  // { code3: "ach", code2: "", name: "Acoli", local: "Lwo" },
  // { code3: "ada", code2: "", name: "Adangme", local: "Dangme" },
  // { code3: "ady", code2: "", name: "Adyghe; Adygei", local: "Адыгабзэ" },
  // {
  //   code3: "afa",
  //   code2: "",
  //   name: "Afro-Asiatic languages",
  //   local: "Afro-Asiatic languages",
  // },
  // { code3: "afh", code2: "", name: "Afrihili", local: "Afrihili" },
  // { code3: "afr", code2: "af", name: "Afrikaans", local: "Afrikaans" },
  // { code3: "ain", code2: "", name: "Ainu", local: "アイヌ・イタㇰ" },
  // { code3: "aka", code2: "ak", name: "Akan", local: "Akan" },
  // { code3: "akk", code2: "", name: "Akkadian", local: "𒀝𒅗𒁺𒌑" },
  // { code3: "alb", code2: "sq", name: "Albanian", local: "Shqip" },
  // { code3: "ale", code2: "", name: "Aleut", local: "Unangam Tunuu" },
  // {
  //   code3: "alg",
  //   code2: "",
  //   name: "Algonquian languages",
  //   local: "Algonquian languages",
  // },
  // { code3: "alt", code2: "", name: "Southern Altai", local: "Алтай тили" },
  // { code3: "amh", code2: "am", name: "Amharic", local: "አማርኛ" },
  // {
  //   code3: "ang",
  //   code2: "",
  //   name: "English, Old (ca.450-1100)",
  //   local: "Englisc",
  // },
  // { code3: "anp", code2: "", name: "Angika", local: "अंगिका" },
  // {
  //   code3: "apa",
  //   code2: "",
  //   name: "Apache languages",
  //   local: "Apache languages",
  // },
  // { code3: "ara", code2: "ar", name: "Arabic", local: "العربية" },
  // {
  //   code3: "arc",
  //   code2: "",
  //   name: "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
  //   local: "ܐܪܡܝܐ",
  // },
  // { code3: "arg", code2: "an", name: "Aragonese", local: "Aragonés" },
  // { code3: "arm", code2: "hy", name: "Armenian", local: "Հայերեն" },
  // { code3: "arn", code2: "", name: "Mapudungun; Mapuche", local: "Mapudungun" },
  // { code3: "arp", code2: "", name: "Arapaho", local: "Hinónoʼeitíít" },
  // {
  //   code3: "art",
  //   code2: "",
  //   name: "Artificial languages",
  //   local: "Artificial languages",
  // },
  // { code3: "arw", code2: "", name: "Arawak", local: "Lokono" },
  // { code3: "asm", code2: "as", name: "Assamese", local: "অসমীয়া" },
  // {
  //   code3: "ast",
  //   code2: "",
  //   name: "Asturian; Bable; Leonese; Asturleonese",
  //   local: "Asturianu",
  // },
  // {
  //   code3: "ath",
  //   code2: "",
  //   name: "Athapascan languages",
  //   local: "Athapascan languages",
  // },
  // {
  //   code3: "aus",
  //   code2: "",
  //   name: "Australian languages",
  //   local: "Australian languages",
  // },
  // { code3: "ava", code2: "av", name: "Avaric", local: "Авар мацӀ" },
  // { code3: "ave", code2: "ae", name: "Avestan", local: "Avesta" },
  // { code3: "awa", code2: "", name: "Awadhi", local: "अवधी" },
  // { code3: "aym", code2: "ay", name: "Aymara", local: "Aymar aru" },
  // { code3: "aze", code2: "az", name: "Azerbaijani", local: "Azərbaycan dili" },
  // {
  //   code3: "bad",
  //   code2: "",
  //   name: "Banda languages",
  //   local: "Banda languages",
  // },
  // {
  //   code3: "bai",
  //   code2: "",
  //   name: "Bamileke languages",
  //   local: "Bamileke languages",
  // },
  // { code3: "bak", code2: "ba", name: "Bashkir", local: "Башҡорт теле" },
  // { code3: "bal", code2: "", name: "Baluchi", local: "بلوچی" },
  // { code3: "bam", code2: "bm", name: "Bambara", local: "Bamanankan" },
  // { code3: "ban", code2: "", name: "Balinese", local: "ᬩᬲᬩᬮᬶ" },
  // { code3: "baq", code2: "eu", name: "Basque", local: "Euskara" },
  // { code3: "bas", code2: "", name: "Basa", local: "Ɓàsàa" },
  // {
  //   code3: "bat",
  //   code2: "",
  //   name: "Baltic languages",
  //   local: "Baltic languages",
  // },
  // { code3: "bej", code2: "", name: "Beja; Bedawiyet", local: "Bidhaawyeet" },
  // { code3: "bel", code2: "be", name: "Belarusian", local: "Беларуская" },
  // { code3: "bem", code2: "", name: "Bemba", local: "Chibemba" },
  // { code3: "ben", code2: "bn", name: "Bengali", local: "বাংলা" },
  // { code3: "ber", code2: "", name: "Berber languages", local: "Tamaziɣt" },
  // { code3: "bho", code2: "", name: "Bhojpuri", local: "भोजपुरी" },
  // { code3: "bih", code2: "bh", name: "Bihari languages", local: "भोजपुरी" },
  // { code3: "bik", code2: "", name: "Bikol", local: "Bikol" },
  // { code3: "bin", code2: "", name: "Bini; Edo", local: "Edo" },
  // { code3: "bis", code2: "bi", name: "Bislama", local: "Bislama" },
  // { code3: "bla", code2: "", name: "Siksika", local: "Siksiká" },
  // {
  //   code3: "bnt",
  //   code2: "",
  //   name: "Bantu languages",
  //   local: "Bantu languages",
  // },
  // { code3: "bod", code2: "bo", name: "Tibetan", local: "བོད་སྐད་" },
  // { code3: "bos", code2: "bs", name: "Bosnian", local: "Bosanski" },
  // { code3: "bra", code2: "", name: "Braj", local: "ब्रज भाषा" },
  // { code3: "bre", code2: "br", name: "Breton", local: "Brezhoneg" },
  // { code3: "btk", code2: "", name: "Batak languages", local: "Batak" },
  // { code3: "bua", code2: "", name: "Buriat", local: "Буряад хэлэн" },
  // { code3: "bug", code2: "", name: "Buginese", local: "ᨅᨔ ᨕᨘᨁᨗ" },
  // { code3: "bul", code2: "bg", name: "Bulgarian", local: "Български" },
  // { code3: "bur", code2: "my", name: "Burmese", local: "မြန်မာစာ" },
  // { code3: "byn", code2: "", name: "Blin; Bilin", local: "ብሊን" },
  // { code3: "cad", code2: "", name: "Caddo", local: "Hasí:nay" },
  // {
  //   code3: "cai",
  //   code2: "",
  //   name: "Central American Indian languages",
  //   local: "Central American Indian languages",
  // },
  // { code3: "car", code2: "", name: "Galibi Carib", local: "Kari'nja" },
  // { code3: "cat", code2: "ca", name: "Catalan", local: "Català" },
  // {
  //   code3: "cau",
  //   code2: "",
  //   name: "Caucasian languages",
  //   local: "Caucasian languages",
  // },
  // { code3: "ceb", code2: "", name: "Cebuano", local: "Cebuano" },
  // {
  //   code3: "cel",
  //   code2: "",
  //   name: "Celtic languages",
  //   local: "Celtic languages",
  // },
  // { code3: "ces", code2: "cs", name: "Czech", local: "Čeština" },
  // { code3: "cha", code2: "ch", name: "Chamorro", local: "Chamoru" },
  // { code3: "chb", code2: "", name: "Chibcha", local: "Chibcha" },
  // { code3: "che", code2: "ce", name: "Chechen", local: "Нохчийн мотт" },
  // { code3: "chg", code2: "", name: "Chagatai", local: "جغتای" },
  // { code3: "chi", code2: "zh", name: "Chinese", local: "中文" },
  // { code3: "chk", code2: "", name: "Chuukese", local: "Chuukese" },
  // { code3: "chm", code2: "", name: "Mari", local: "Марий йылме" },
  // { code3: "chn", code2: "", name: "Chinook jargon", local: "Chinook Wawa" },
  // { code3: "cho", code2: "", name: "Choctaw", local: "Chahta'" },
  // {
  //   code3: "chp",
  //   code2: "",
  //   name: "Chipewyan; Dene Suline",
  //   local: "Dëne Sųłiné",
  // },
  // { code3: "chr", code2: "", name: "Cherokee", local: "ᏣᎳᎩ" },
  // { code3: "chu", code2: "cu", name: "Church Slavic", local: "Словѣньскъ" },
  // { code3: "chv", code2: "cv", name: "Chuvash", local: "Чӑвашла" },
  // { code3: "chy", code2: "", name: "Cheyenne", local: "Tsėhésenėstsestotse" },
  // {
  //   code3: "cmc",
  //   code2: "",
  //   name: "Chamic languages",
  //   local: "Chamic languages",
  // },
  // { code3: "cnr", code2: "", name: "Montenegrin", local: "Crnogorski" },
  // { code3: "cop", code2: "", name: "Coptic", local: "ⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ" },
  // { code3: "cor", code2: "kw", name: "Cornish", local: "Kernewek" },
  // { code3: "cos", code2: "co", name: "Corsican", local: "Corsu" },
  // {
  //   code3: "cpe",
  //   code2: "",
  //   name: "Creoles and pidgins, English based",
  //   local: "English-based Creoles and pidgins",
  // },
  // {
  //   code3: "cpf",
  //   code2: "",
  //   name: "Creoles and pidgins, French-based",
  //   local: "French-based Creoles and pidgins",
  // },
  // {
  //   code3: "cpp",
  //   code2: "",
  //   name: "Creoles and pidgins, Portuguese-based",
  //   local: "Portuguese-based Creoles and pidgins",
  // },
  // { code3: "cre", code2: "cr", name: "Cree", local: "ᓀᐦᐃᔭᐍᐏᐣ" },
  // {
  //   code3: "crh",
  //   code2: "",
  //   name: "Crimean Tatar; Crimean Turkish",
  //   local: "Qırımtatarca",
  // },
  // {
  //   code3: "crp",
  //   code2: "",
  //   name: "Creoles and pidgins",
  //   local: "Creoles and pidgins",
  // },
  // { code3: "csb", code2: "", name: "Kashubian", local: "Kaszëbsczi" },
  // {
  //   code3: "cus",
  //   code2: "",
  //   name: "Cushitic languages",
  //   local: "Cushitic languages",
  // },
  // { code3: "cym", code2: "cy", name: "Welsh", local: "Cymraeg" },
  // { code3: "cze", code2: "cs", name: "Czech", local: "Čeština" },
  // { code3: "dak", code2: "", name: "Dakota", local: "Dakȟótiyapi" },
  // { code3: "dan", code2: "da", name: "Danish", local: "Dansk" },
  // { code3: "dar", code2: "", name: "Dargwa", local: "Дарган мез" },
  // {
  //   code3: "day",
  //   code2: "",
  //   name: "Land Dayak languages",
  //   local: "Land Dayak languages",
  // },
  // { code3: "del", code2: "", name: "Delaware", local: "Lënape" },
  // { code3: "den", code2: "", name: "Slave (Athapascan)", local: "Dene" },
  // { code3: "deu", code2: "de", name: "German", local: "Deutsch" },
  // { code3: "dgr", code2: "", name: "Dogrib", local: "Tłı̨chǫ" },
  // { code3: "din", code2: "", name: "Dinka", local: "Thuɔŋjäŋ" },
  // {
  //   code3: "div",
  //   code2: "dv",
  //   name: "Divehi; Dhivehi; Maldivian",
  //   local: "ދިވެހި",
  // },
  // { code3: "doi", code2: "", name: "Dogri", local: "डोगरी" },
  // {
  //   code3: "dra",
  //   code2: "",
  //   name: "Dravidian languages",
  //   local: "Dravidian languages",
  // },
  // { code3: "dsb", code2: "", name: "Lower Sorbian", local: "Dolnoserbski" },
  // { code3: "dua", code2: "", name: "Duala", local: "Duala" },
  // {
  //   code3: "dum",
  //   code2: "",
  //   name: "Dutch, Middle (ca.1050-1350)",
  //   local: "Middelnederlands",
  // },
  // { code3: "dut", code2: "nl", name: "Dutch; Flemish", local: "Nederlands" },
  // { code3: "dyu", code2: "", name: "Dyula", local: "Julakan" },
  // { code3: "dzo", code2: "dz", name: "Dzongkha", local: "རྫོང་ཁ" },
  // { code3: "efi", code2: "", name: "Efik", local: "Efịk" },
  // { code3: "egy", code2: "", name: "Egyptian (Ancient)", local: "r n km.t" },
  // { code3: "eka", code2: "", name: "Ekajuk", local: "Ekajuk" },
  // { code3: "ell", code2: "el", name: "Greek", local: "Ελληνικά" },
  // { code3: "elx", code2: "", name: "Elamite", local: "𒉎𒆷𒂵𒈨" },
  { code3: "eng", code2: "en", name: "English", local: "English" },
  // {
  //   code3: "enm",
  //   code2: "",
  //   name: "English, Middle (1100-1500)",
  //   local: "Middle English",
  // },
  // { code3: "epo", code2: "eo", name: "Esperanto", local: "Esperanto" },
  // { code3: "est", code2: "et", name: "Estonian", local: "Eesti" },
  // { code3: "eus", code2: "eu", name: "Basque", local: "Euskara" },
  // { code3: "ewe", code2: "ee", name: "Ewe", local: "Eʋegbe" },
  // { code3: "ewo", code2: "", name: "Ewondo", local: "Ewondo" },
  // { code3: "fan", code2: "", name: "Fang", local: "Fang" },
  // { code3: "fao", code2: "fo", name: "Faroese", local: "Føroyskt" },
  // { code3: "fas", code2: "fa", name: "Persian", local: "فارسی" },
  // { code3: "fat", code2: "", name: "Fanti", local: "Fante" },
  // { code3: "fij", code2: "fj", name: "Fijian", local: "Vosa Vakaviti" },
  // { code3: "fil", code2: "", name: "Filipino; Pilipino", local: "Filipino" },
  // { code3: "fin", code2: "fi", name: "Finnish", local: "Suomi" },
  // {
  //   code3: "fiu",
  //   code2: "",
  //   name: "Finno-Ugrian languages",
  //   local: "Finno-Ugrian languages",
  // },
  // { code3: "fon", code2: "", name: "Fon", local: "Fon gbè" },
  // { code3: "fra", code2: "fr", name: "French", local: "Français" },
  // { code3: "fre", code2: "fr", name: "French", local: "Français" },
  // {
  //   code3: "frm",
  //   code2: "",
  //   name: "French, Middle (ca.1400-1600)",
  //   local: "Moyen Français",
  // },
  // {
  //   code3: "fro",
  //   code2: "",
  //   name: "French, Old (842-ca.1400)",
  //   local: "Ancien Français",
  // },
  // { code3: "frr", code2: "", name: "Northern Frisian", local: "Nordfriisk" },
  // { code3: "frs", code2: "", name: "Eastern Frisian", local: "Seeltersk" },
  // { code3: "fry", code2: "fy", name: "Western Frisian", local: "Frysk" },
  // { code3: "ful", code2: "ff", name: "Fulah", local: "Fulfulde" },
  // { code3: "fur", code2: "", name: "Friulian", local: "Furlan" },
  // { code3: "gaa", code2: "", name: "Ga", local: "Gã" },
  // { code3: "gay", code2: "", name: "Gayo", local: "Gayo" },
  // { code3: "gba", code2: "", name: "Gbaya", local: "Gbaya" },
  // {
  //   code3: "gem",
  //   code2: "",
  //   name: "Germanic languages",
  //   local: "Germanic languages",
  // },
  // { code3: "geo", code2: "ka", name: "Georgian", local: "ქართული" },
  // { code3: "ger", code2: "de", name: "German", local: "Deutsch" },
  // { code3: "gez", code2: "", name: "Geez", local: "ግዕዝ" },
  // { code3: "gil", code2: "", name: "Gilbertese", local: "Taetae ni Kiribati" },
  // {
  //   code3: "gla",
  //   code2: "gd",
  //   name: "Gaelic; Scottish Gaelic",
  //   local: "Gàidhlig",
  // },
  // { code3: "gle", code2: "ga", name: "Irish", local: "Gaeilge" },
  // { code3: "glg", code2: "gl", name: "Galician", local: "Galego" },
  // { code3: "glv", code2: "gv", name: "Manx", local: "Gaelg" },
  // {
  //   code3: "gmh",
  //   code2: "",
  //   name: "German, Middle High (ca.1050-1500)",
  //   local: "Mittelhochdeutsch",
  // },
  // {
  //   code3: "goh",
  //   code2: "",
  //   name: "German, Old High (ca.750-1050)",
  //   local: "Althochdeutsch",
  // },
  // { code3: "gon", code2: "", name: "Gondi", local: "Gōndi" },
  // { code3: "gor", code2: "", name: "Gorontalo", local: "Bahasa Hulontalo" },
  // { code3: "got", code2: "", name: "Gothic", local: "𐌲𐌿𐍄𐌹𐍃𐌺" },
  // { code3: "grb", code2: "", name: "Grebo", local: "Grebo" },
  // { code3: "grc", code2: "", name: "Ancient Greek", local: "Ἑλληνική" },
  // { code3: "gre", code2: "el", name: "Greek", local: "Ελληνικά" },
  // { code3: "grn", code2: "gn", name: "Guarani", local: "Avañe'ẽ" },
  // {
  //   code3: "gsw",
  //   code2: "",
  //   name: "Swiss German; Alemannic; Alsatian",
  //   local: "Schwyzerdütsch",
  // },
  // { code3: "guj", code2: "gu", name: "Gujarati", local: "ગુજરાતી" },
  // { code3: "gwi", code2: "", name: "Gwich'in", local: "Dinjii Zhu' Ginjik" },
  // { code3: "hai", code2: "", name: "Haida", local: "X̱aat Kíl" },
  // {
  //   code3: "hat",
  //   code2: "ht",
  //   name: "Haitian; Haitian Creole",
  //   local: "Kreyòl Ayisyen",
  // },
  // { code3: "hau", code2: "ha", name: "Hausa", local: "هَوُسَ" },
  // { code3: "haw", code2: "", name: "Hawaiian", local: "ʻŌlelo Hawaiʻi" },
  // { code3: "heb", code2: "he", name: "Hebrew", local: "עברית" },
  // { code3: "her", code2: "hz", name: "Herero", local: "Otjiherero" },
  // { code3: "hil", code2: "", name: "Hiligaynon", local: "Ilonggo" },
  // {
  //   code3: "him",
  //   code2: "",
  //   name: "Himachali languages; Western Pahari languages",
  //   local: "पहाड़ी",
  // },
  // { code3: "hin", code2: "hi", name: "Hindi", local: "हिन्दी" },
  // { code3: "hit", code2: "", name: "Hittite", local: "𒉈𒅆𒇷" },
  // { code3: "hmn", code2: "", name: "Hmong; Mong", local: "Hmoob" },
  // { code3: "hmo", code2: "ho", name: "Hiri Motu", local: "Hiri Motu" },
  // { code3: "hrv", code2: "hr", name: "Croatian", local: "Hrvatski" },
  // { code3: "hsb", code2: "", name: "Upper Sorbian", local: "Hornjoserbsce" },
  // { code3: "hun", code2: "hu", name: "Hungarian", local: "Magyar" },
  // { code3: "hup", code2: "", name: "Hupa", local: "Na:tinixwe Mixine:whe'" },
  // { code3: "hye", code2: "hy", name: "Armenian", local: "Հայերեն" },
  // { code3: "iba", code2: "", name: "Iban", local: "Iban" },
  // { code3: "ibo", code2: "ig", name: "Igbo", local: "Igbo" },
  // { code3: "ice", code2: "is", name: "Icelandic", local: "Íslenska" },
  // { code3: "ido", code2: "io", name: "Ido", local: "Ido" },
  // { code3: "iii", code2: "ii", name: "Sichuan Yi; Nuosu", local: "ꆈꌠꉙ" },
  // { code3: "ijo", code2: "", name: "Ijo languages", local: "Ijo" },
  // { code3: "iku", code2: "iu", name: "Inuktitut", local: "ᐃᓄᒃᑎᑐᑦ" },
  // { code3: "ile", code2: "ie", name: "Interlingue", local: "Interlingue" },
  // { code3: "ilo", code2: "", name: "Iloko", local: "Ilokano" },
  // { code3: "ina", code2: "ia", name: "Interlingua", local: "Interlingua" },
  // {
  //   code3: "inc",
  //   code2: "",
  //   name: "Indic languages",
  //   local: "Indic languages",
  // },
  // { code3: "ind", code2: "id", name: "Indonesian", local: "Bahasa Indonesia" },
  // {
  //   code3: "ine",
  //   code2: "",
  //   name: "Indo-European languages",
  //   local: "Indo-European languages",
  // },
  // { code3: "inh", code2: "", name: "Ingush", local: "ГӀалгӀай мотт" },
  // { code3: "ipk", code2: "ik", name: "Inupiaq", local: "Iñupiaq" },
  // {
  //   code3: "ira",
  //   code2: "",
  //   name: "Iranian languages",
  //   local: "Iranian languages",
  // },
  // {
  //   code3: "iro",
  //   code2: "",
  //   name: "Iroquoian languages",
  //   local: "Iroquoian languages",
  // },
  // { code3: "isl", code2: "is", name: "Icelandic", local: "Íslenska" },
  // { code3: "ita", code2: "it", name: "Italian", local: "Italiano" },
  // { code3: "jav", code2: "jv", name: "Javanese", local: "Basa Jawa" },
  // { code3: "jbo", code2: "", name: "Lojban", local: "Lojban" },
  // { code3: "jpn", code2: "ja", name: "Japanese", local: "日本語" },
  // { code3: "jpr", code2: "", name: "Judeo-Persian", local: "Dzhidi" },
  // { code3: "jrb", code2: "", name: "Judeo-Arabic", local: "Yahudic" },
  // { code3: "kaa", code2: "", name: "Kara-Kalpak", local: "Қарақалпақ тили" },
  // { code3: "kab", code2: "", name: "Kabyle", local: "Taqbaylit" },
  // { code3: "kac", code2: "", name: "Kachin; Jingpho", local: "Jinghpaw" },
  // { code3: "kal", code2: "kl", name: "Kalaallisut", local: "Kalaallisut" },
  // { code3: "kam", code2: "", name: "Kamba", local: "Kikamba" },
  // { code3: "kan", code2: "kn", name: "Kannada", local: "ಕನ್ನಡ" },
  // {
  //   code3: "kar",
  //   code2: "",
  //   name: "Karen languages",
  //   local: "Karen languages",
  // },
  // { code3: "kas", code2: "ks", name: "Kashmiri", local: "कॉशुर" },
  // { code3: "kat", code2: "ka", name: "Georgian", local: "ქართული" },
  // { code3: "kau", code2: "kr", name: "Kanuri", local: "Kanuri" },
  // { code3: "kaw", code2: "", name: "Kawi", local: "Kawi" },
  // { code3: "kaz", code2: "kk", name: "Kazakh", local: "Қазақ тілі" },
  // { code3: "kbd", code2: "", name: "Kabardian", local: "Адыгэбзэ" },
  // { code3: "kha", code2: "", name: "Khasi", local: "Khasi" },
  // {
  //   code3: "khi",
  //   code2: "",
  //   name: "Khoisan languages",
  //   local: "Khoisan languages",
  // },
  // { code3: "khm", code2: "km", name: "Central Khmer", local: "ភាសាខ្មែរ" },
  // { code3: "kho", code2: "", name: "Khotanese; Sakan", local: "Khotanese" },
  // { code3: "kik", code2: "ki", name: "Kikuyu; Gikuyu", local: "Gĩkũyũ" },
  // { code3: "kin", code2: "rw", name: "Kinyarwanda", local: "Kinyarwanda" },
  // { code3: "kir", code2: "ky", name: "Kirghiz; Kyrgyz", local: "Кыргызча" },
  // { code3: "kmb", code2: "", name: "Kimbundu", local: "Kimbundu" },
  // { code3: "kok", code2: "", name: "Konkani", local: "कोंकणी" },
  // { code3: "kom", code2: "kv", name: "Komi", local: "Коми кыв" },
  // { code3: "kon", code2: "kg", name: "Kongo", local: "Kikongo" },
  // { code3: "kor", code2: "ko", name: "Korean", local: "한국어" },
  // { code3: "kos", code2: "", name: "Kosraean", local: "Kosraean" },
  // { code3: "kpe", code2: "", name: "Kpelle", local: "Kpɛlɛɛ" },
  // {
  //   code3: "krc",
  //   code2: "",
  //   name: "Karachay-Balkar",
  //   local: "Къарачай-Малкъар тил",
  // },
  // { code3: "krl", code2: "", name: "Karelian", local: "Karjalan kieli" },
  // { code3: "kro", code2: "", name: "Kru languages", local: "Kru languages" },
  // { code3: "kru", code2: "", name: "Kurukh", local: "कुड़ुख़" },
  // {
  //   code3: "kua",
  //   code2: "kj",
  //   name: "Kuanyama; Kwanyama",
  //   local: "Oshikwanyama",
  // },
  // { code3: "kum", code2: "", name: "Kumyk", local: "Къумукъ тил" },
  // { code3: "kur", code2: "ku", name: "Kurdish", local: "Kurdî" },
  // { code3: "kut", code2: "", name: "Kutenai", local: "Ktunaxa" },
  // { code3: "lad", code2: "", name: "Ladino", local: "Judeo-español" },
  // { code3: "lah", code2: "", name: "Lahnda", local: "لہندا" },
  // { code3: "lam", code2: "", name: "Lamba", local: "Lamba" },
  // { code3: "lao", code2: "lo", name: "Lao", local: "ພາສາລາວ" },
  // { code3: "lat", code2: "la", name: "Latin", local: "Latina" },
  // { code3: "lav", code2: "lv", name: "Latvian", local: "Latviešu" },
  // { code3: "lez", code2: "", name: "Lezghian", local: "Лезги чӀал" },
  // { code3: "lim", code2: "li", name: "Limburgish", local: "Limburgs" },
  // { code3: "lin", code2: "ln", name: "Lingala", local: "Lingála" },
  // { code3: "lit", code2: "lt", name: "Lithuanian", local: "Lietuvių" },
  // { code3: "lol", code2: "", name: "Mongo", local: "Lomongo" },
  // { code3: "loz", code2: "", name: "Lozi", local: "Silozi" },
  // { code3: "ltz", code2: "lb", name: "Luxembourgish", local: "Lëtzebuergesch" },
  // { code3: "lua", code2: "", name: "Luba-Lulua", local: "Tshiluba" },
  // { code3: "lub", code2: "lu", name: "Luba-Katanga", local: "Kiluba" },
  // { code3: "lug", code2: "lg", name: "Ganda", local: "Luganda" },
  // { code3: "lui", code2: "", name: "Luiseno", local: "Luiseño" },
  // { code3: "lun", code2: "", name: "Lunda", local: "Chilunda" },
  // {
  //   code3: "luo",
  //   code2: "",
  //   name: "Luo (Kenya and Tanzania)",
  //   local: "Dholuo",
  // },
  // { code3: "lus", code2: "", name: "Lushai", local: "Mizo ṭawng" },
  // { code3: "mac", code2: "mk", name: "Macedonian", local: "Македонски" },
  // { code3: "mad", code2: "", name: "Madurese", local: "Madhura" },
  // { code3: "mag", code2: "", name: "Magahi", local: "मगही" },
  // { code3: "mah", code2: "mh", name: "Marshallese", local: "Kajin M̧ajeļ" },
  // { code3: "mai", code2: "", name: "Maithili", local: "मैथिली" },
  // { code3: "mak", code2: "", name: "Makasar", local: "Basa Mangkasara" },
  // { code3: "mal", code2: "ml", name: "Malayalam", local: "മലയാളം" },
  // { code3: "man", code2: "", name: "Mandingo", local: "Mandinka" },
  // { code3: "mao", code2: "mi", name: "Maori", local: "Te Reo Māori" },
  // {
  //   code3: "map",
  //   code2: "",
  //   name: "Austronesian languages",
  //   local: "Austronesian languages",
  // },
  // { code3: "mar", code2: "mr", name: "Marathi", local: "मराठी" },
  // { code3: "mas", code2: "", name: "Masai", local: "ɔl Maa" },
  // { code3: "may", code2: "ms", name: "Malay", local: "Bahasa Melayu" },
  // { code3: "mdf", code2: "", name: "Moksha", local: "Мокшень кяль" },
  // { code3: "mdr", code2: "", name: "Mandar", local: "Bahasa Mandar" },
  // { code3: "men", code2: "", name: "Mende", local: "Mɛnde" },
  // {
  //   code3: "mga",
  //   code2: "",
  //   name: "Irish, Middle (900-1200)",
  //   local: "Gaeilge Mheánaoiseach",
  // },
  // { code3: "mic", code2: "", name: "Mi'kmaq; Micmac", local: "Miꞌkmaq" },
  // { code3: "min", code2: "", name: "Minangkabau", local: "Baso Minangkabau" },
  // {
  //   code3: "mis",
  //   code2: "",
  //   name: "Uncoded languages",
  //   local: "Uncoded languages",
  // },
  // { code3: "mkd", code2: "mk", name: "Macedonian", local: "Македонски" },
  // {
  //   code3: "mkh",
  //   code2: "",
  //   name: "Mon-Khmer languages",
  //   local: "Mon-Khmer languages",
  // },
  // { code3: "mlg", code2: "mg", name: "Malagasy", local: "Malagasy" },
  // { code3: "mlt", code2: "mt", name: "Maltese", local: "Malti" },
  // { code3: "mnc", code2: "", name: "Manchu", local: "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ" },
  // { code3: "mni", code2: "", name: "Manipuri", local: "মৈতৈলোন্" },
  // {
  //   code3: "mno",
  //   code2: "",
  //   name: "Manobo languages",
  //   local: "Manobo languages",
  // },
  // { code3: "moh", code2: "", name: "Mohawk", local: "Kanien'kéha" },
  // { code3: "mon", code2: "mn", name: "Mongolian", local: "Монгол хэл" },
  // { code3: "mos", code2: "", name: "Mossi", local: "Mooré" },
  // { code3: "mri", code2: "mi", name: "Maori", local: "Te Reo Māori" },
  // { code3: "msa", code2: "ms", name: "Malay", local: "Bahasa Melayu" },
  // {
  //   code3: "mul",
  //   code2: "",
  //   name: "Multiple languages",
  //   local: "Multiple languages",
  // },
  // {
  //   code3: "mun",
  //   code2: "",
  //   name: "Munda languages",
  //   local: "Munda languages",
  // },
  // { code3: "mus", code2: "", name: "Creek", local: "Mvskoke" },
  // { code3: "mwl", code2: "", name: "Mirandese", local: "Mirandés" },
  // { code3: "mwr", code2: "", name: "Marwari", local: "मारवाड़ी" },
  // { code3: "mya", code2: "my", name: "Burmese", local: "မြန်မာစာ" },
  // {
  //   code3: "myn",
  //   code2: "",
  //   name: "Mayan languages",
  //   local: "Mayan languages",
  // },
  // { code3: "myv", code2: "", name: "Erzya", local: "Эрзянь кель" },
  // { code3: "nah", code2: "", name: "Nahuatl languages", local: "Nāhuatl" },
  // {
  //   code3: "nai",
  //   code2: "",
  //   name: "North American Indian languages",
  //   local: "North American Indian languages",
  // },
  // { code3: "nap", code2: "", name: "Neapolitan", local: "Napulitano" },
  // { code3: "nau", code2: "na", name: "Nauru", local: "Dorerin Naoero" },
  // { code3: "nav", code2: "nv", name: "Navajo", local: "Diné bizaad" },
  // { code3: "nbl", code2: "nr", name: "South Ndebele", local: "isiNdebele" },
  // { code3: "nde", code2: "nd", name: "North Ndebele", local: "isiNdebele" },
  // { code3: "ndo", code2: "ng", name: "Ndonga", local: "Oshiwambo" },
  // {
  //   code3: "nds",
  //   code2: "",
  //   name: "Low German; Low Saxon; German, Low; Saxon, Low",
  //   local: "Plattdüütsch",
  // },
  // { code3: "nep", code2: "ne", name: "Nepali", local: "नेपाली" },
  // { code3: "new", code2: "", name: "Nepal Bhasa; Newari", local: "नेपाल भाषा" },
  // { code3: "nia", code2: "", name: "Nias", local: "Li Niha" },
  // {
  //   code3: "nic",
  //   code2: "",
  //   name: "Niger-Kordofanian languages",
  //   local: "Niger-Kordofanian languages",
  // },
  // { code3: "niu", code2: "", name: "Niuean", local: "ko e vagahau Niuē" },
  // { code3: "nld", code2: "nl", name: "Dutch; Flemish", local: "Nederlands" },
  // { code3: "nno", code2: "nn", name: "Norwegian Nynorsk", local: "Nynorsk" },
  // { code3: "nob", code2: "nb", name: "Norwegian Bokmål", local: "Bokmål" },
  // { code3: "nog", code2: "", name: "Nogai", local: "Ногай тили" },
  // { code3: "non", code2: "", name: "Norse, Old", local: "Norrœnt" },
  // { code3: "nor", code2: "no", name: "Norwegian", local: "Norsk" },
  // { code3: "nqo", code2: "", name: "N'Ko", local: "ߒߞߏ" },
  // {
  //   code3: "nso",
  //   code2: "",
  //   name: "Pedi; Sepedi; Northern Sotho",
  //   local: "Sesotho sa Leboa",
  // },
  // {
  //   code3: "nub",
  //   code2: "",
  //   name: "Nubian languages",
  //   local: "Nubian languages",
  // },
  // {
  //   code3: "nwc",
  //   code2: "",
  //   name: "Classical Newari; Old Newari; Classical Nepal Bhasa",
  //   local: "नेवाः भाय्",
  // },
  // {
  //   code3: "nya",
  //   code2: "ny",
  //   name: "Chichewa; Chewa; Nyanja",
  //   local: "Chichewa",
  // },
  // { code3: "nym", code2: "", name: "Nyamwezi", local: "Kinyamwezi" },
  // { code3: "nyn", code2: "", name: "Nyankole", local: "Runyankore" },
  // { code3: "nyo", code2: "", name: "Nyoro", local: "Runyoro" },
  // { code3: "nzi", code2: "", name: "Nzima", local: "Nzema" },
  // { code3: "oci", code2: "oc", name: "Occitan (post 1500)", local: "Occitan" },
  // { code3: "oji", code2: "oj", name: "Ojibwa", local: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
  // { code3: "ori", code2: "or", name: "Oriya", local: "ଓଡ଼ିଆ" },
  // { code3: "orm", code2: "om", name: "Oromo", local: "Afaan Oromoo" },
  // { code3: "osa", code2: "", name: "Osage", local: "Wazhazhe ie" },
  // { code3: "oss", code2: "os", name: "Ossetian; Ossetic", local: "Ирон æвзаг" },
  // {
  //   code3: "ota",
  //   code2: "",
  //   name: "Turkish, Ottoman (1500-1928)",
  //   local: "لسان عثمانى",
  // },
  // {
  //   code3: "oto",
  //   code2: "",
  //   name: "Otomian languages",
  //   local: "Otomian languages",
  // },
  // {
  //   code3: "paa",
  //   code2: "",
  //   name: "Papuan languages",
  //   local: "Papuan languages",
  // },
  // { code3: "pag", code2: "", name: "Pangasinan", local: "Pangasinan" },
  // { code3: "pal", code2: "", name: "Pahlavi", local: "Pahlavi" },
  // {
  //   code3: "pam",
  //   code2: "",
  //   name: "Pampanga; Kapampangan",
  //   local: "Kapampangan",
  // },
  // { code3: "pan", code2: "pa", name: "Panjabi; Punjabi", local: "ਪੰਜਾਬੀ" },
  // { code3: "pap", code2: "", name: "Papiamento", local: "Papiamentu" },
  // { code3: "pau", code2: "", name: "Palauan", local: "a tekoi er a Belau" },
  // {
  //   code3: "peo",
  //   code2: "",
  //   name: "Persian, Old (ca.600-400 B.C.)",
  //   local: "𐎱𐎠𐎼𐎿",
  // },
  // { code3: "per", code2: "fa", name: "Persian", local: "فارسی" },
  // {
  //   code3: "phi",
  //   code2: "",
  //   name: "Philippine languages",
  //   local: "Philippine languages",
  // },
  // { code3: "phn", code2: "", name: "Phoenician", local: "𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌" },
  // { code3: "pli", code2: "pi", name: "Pali", local: "पालि" },
  // { code3: "pol", code2: "pl", name: "Polish", local: "Polski" },
  // { code3: "pon", code2: "", name: "Pohnpeian", local: "Pohnpeian" },
  // { code3: "por", code2: "pt", name: "Portuguese", local: "Português" },
  // {
  //   code3: "pra",
  //   code2: "",
  //   name: "Prakrit languages",
  //   local: "Prakrit languages",
  // },
  // {
  //   code3: "pro",
  //   code2: "",
  //   name: "Provençal, Old (to 1500);Occitan, Old (to 1500)",
  //   local: "Provençal",
  // },
  // { code3: "pus", code2: "ps", name: "Pushto; Pashto", local: "پښتو" },
  // {
  //   code3: "qaa-qtz",
  //   code2: "",
  //   name: "Reserved for local use",
  //   local: "Reserved for local use",
  // },
  // { code3: "que", code2: "qu", name: "Quechua", local: "Runa Simi" },
  // { code3: "raj", code2: "", name: "Rajasthani", local: "राजस्थानी" },
  // { code3: "rap", code2: "", name: "Rapanui", local: "Vananga rapa nui" },
  // {
  //   code3: "rar",
  //   code2: "",
  //   name: "Rarotongan; Cook Islands Maori",
  //   local: "Māori Kūki 'Āirani",
  // },
  // {
  //   code3: "roa",
  //   code2: "",
  //   name: "Romance languages",
  //   local: "Romance languages",
  // },
  // { code3: "roh", code2: "rm", name: "Romansh", local: "Rumantsch" },
  // { code3: "rom", code2: "", name: "Romany", local: "Romani" },
  // {
  //   code3: "ron",
  //   code2: "ro",
  //   name: "Romanian; Moldavian; Moldovan",
  //   local: "Română",
  // },
  // {
  //   code3: "rum",
  //   code2: "ro",
  //   name: "Romanian; Moldavian; Moldovan",
  //   local: "Română",
  // },
  // { code3: "run", code2: "rn", name: "Rundi", local: "Kirundi" },
  // {
  //   code3: "rup",
  //   code2: "",
  //   name: "Aromanian; Arumanian; Macedo-Romanian",
  //   local: "Armãneashti",
  // },
  // { code3: "rus", code2: "ru", name: "Russian", local: "Русский" },
  // { code3: "sad", code2: "", name: "Sandawe", local: "Sandawe" },
  // { code3: "sag", code2: "sg", name: "Sango", local: "Sängö" },
  // { code3: "sah", code2: "", name: "Yakut", local: "Саха тыла" },
  // {
  //   code3: "sai",
  //   code2: "",
  //   name: "South American Indian languages",
  //   local: "South American Indian languages",
  // },
  // {
  //   code3: "sal",
  //   code2: "",
  //   name: "Salishan languages",
  //   local: "Salishan languages",
  // },
  // {
  //   code3: "sam",
  //   code2: "",
  //   name: "Samaritan Aramaic",
  //   local: "ארמית שומרונית",
  // },
  // { code3: "san", code2: "sa", name: "Sanskrit", local: "संस्कृतम्" },
  // { code3: "sas", code2: "", name: "Sasak", local: "Basa Sasak" },
  // { code3: "sat", code2: "", name: "Santali", local: "ᱥᱟᱱᱛᱟᱲᱤ" },
  // { code3: "scn", code2: "", name: "Sicilian", local: "Sicilianu" },
  // { code3: "sco", code2: "", name: "Scots", local: "Scots" },
  // { code3: "sel", code2: "", name: "Selkup", local: "Шӧльӄумыт әты" },
  // {
  //   code3: "sem",
  //   code2: "",
  //   name: "Semitic languages",
  //   local: "Semitic languages",
  // },
  // { code3: "sga", code2: "", name: "Irish, Old (to 900)", local: "Goídelc" },
  // { code3: "sgn", code2: "", name: "Sign Languages", local: "Sign Languages" },
  // { code3: "shn", code2: "", name: "Shan", local: "ၽႃႇသႃႇတႆး" },
  // { code3: "sid", code2: "", name: "Sidamo", local: "Sidaamu Afoo" },
  // { code3: "sin", code2: "si", name: "Sinhala; Sinhalese", local: "සිංහල" },
  // {
  //   code3: "sio",
  //   code2: "",
  //   name: "Siouan languages",
  //   local: "Siouan languages",
  // },
  // {
  //   code3: "sit",
  //   code2: "",
  //   name: "Sino-Tibetan languages",
  //   local: "Sino-Tibetan languages",
  // },
  // {
  //   code3: "sla",
  //   code2: "",
  //   name: "Slavic languages",
  //   local: "Slavic languages",
  // },
  // { code3: "slk", code2: "sk", name: "Slovak", local: "Slovenčina" },
  // { code3: "slo", code2: "sk", name: "Slovak", local: "Slovenčina" },
  // { code3: "slv", code2: "sl", name: "Slovenian", local: "Slovenščina" },
  // {
  //   code3: "sma",
  //   code2: "",
  //   name: "Southern Sami",
  //   local: "Åarjelsaemien gïele",
  // },
  // {
  //   code3: "sme",
  //   code2: "se",
  //   name: "Northern Sami",
  //   local: "Davvisámegiella",
  // },
  // { code3: "smi", code2: "", name: "Sami languages", local: "Sami languages" },
  // { code3: "smj", code2: "", name: "Lule Sami", local: "Julevsámegiella" },
  // { code3: "smn", code2: "", name: "Inari Sami", local: "Anarâškielâ" },
  // { code3: "smo", code2: "sm", name: "Samoan", local: "Gagana fa'a Sāmoa" },
  // { code3: "sms", code2: "", name: "Skolt Sami", local: "Sääʹmǩiõll" },
  // { code3: "sna", code2: "sn", name: "Shona", local: "chiShona" },
  // { code3: "snd", code2: "sd", name: "Sindhi", local: "سنڌي" },
  // { code3: "snk", code2: "", name: "Soninke", local: "Soninkanxaane" },
  // { code3: "sog", code2: "", name: "Sogdian", local: "Sogdian" },
  // { code3: "som", code2: "so", name: "Somali", local: "Soomaali" },
  // {
  //   code3: "son",
  //   code2: "",
  //   name: "Songhai languages",
  //   local: "Songhai languages",
  // },
  // { code3: "sot", code2: "st", name: "Sotho, Southern", local: "Sesotho" },
  // { code3: "spa", code2: "es", name: "Spanish; Castilian", local: "Español" },
  // { code3: "sqi", code2: "sq", name: "Albanian", local: "Shqip" },
  // { code3: "srd", code2: "sc", name: "Sardinian", local: "Sardu" },
  // { code3: "srn", code2: "", name: "Sranan Tongo", local: "Sranantongo" },
  // { code3: "srp", code2: "sr", name: "Serbian", local: "Српски" },
  // { code3: "srr", code2: "", name: "Serer", local: "Seereer" },
  // {
  //   code3: "ssa",
  //   code2: "",
  //   name: "Nilo-Saharan languages",
  //   local: "Nilo-Saharan languages",
  // },
  // { code3: "ssw", code2: "ss", name: "Swati", local: "SiSwati" },
  // { code3: "suk", code2: "", name: "Sukuma", local: "Kisukuma" },
  // { code3: "sun", code2: "su", name: "Sundanese", local: "Basa Sunda" },
  // { code3: "sus", code2: "", name: "Susu", local: "Sosoxui" },
  // { code3: "sux", code2: "", name: "Sumerian", local: "𒅴𒂠" },
  // { code3: "swa", code2: "sw", name: "Swahili", local: "Kiswahili" },
  // { code3: "swe", code2: "sv", name: "Swedish", local: "Svenska" },
  // { code3: "syc", code2: "", name: "Classical Syriac", local: "ܠܫܢܐ ܣܘܪܝܝܐ" },
  // { code3: "syr", code2: "", name: "Syriac", local: "ܣܘܪܝܝܐ" },
  // { code3: "tah", code2: "ty", name: "Tahitian", local: "Reo Tahiti" },
  // { code3: "tai", code2: "", name: "Tai languages", local: "Tai languages" },
  // { code3: "tam", code2: "ta", name: "Tamil", local: "தமிழ்" },
  // { code3: "tat", code2: "tt", name: "Tatar", local: "Татар теле" },
  // { code3: "tel", code2: "te", name: "Telugu", local: "తెలుగు" },
  // { code3: "tem", code2: "", name: "Timne", local: "Themne" },
  // { code3: "ter", code2: "", name: "Tereno", local: "Terêna" },
  // { code3: "tet", code2: "", name: "Tetum", local: "Tetun" },
  // { code3: "tgk", code2: "tg", name: "Tajik", local: "Тоҷикӣ" },
  // { code3: "tgl", code2: "tl", name: "Tagalog", local: "Tagalog" },
  // { code3: "tha", code2: "th", name: "Thai", local: "ไทย" },
  // { code3: "tib", code2: "bo", name: "Tibetan", local: "བོད་སྐད་" },
  // { code3: "tig", code2: "", name: "Tigre", local: "ትግረ" },
  // { code3: "tir", code2: "ti", name: "Tigrinya", local: "ትግርኛ" },
  // { code3: "tiv", code2: "", name: "Tiv", local: "Tiv" },
  // { code3: "tkl", code2: "", name: "Tokelau", local: "Tokelau" },
  // {
  //   code3: "tlh",
  //   code2: "",
  //   name: "Klingon; tlhIngan-Hol",
  //   local: "tlhIngan Hol",
  // },
  // { code3: "tli", code2: "", name: "Tlingit", local: "Lingít" },
  // { code3: "tmh", code2: "", name: "Tamashek", local: "Tamajeq" },
  // { code3: "tog", code2: "", name: "Tonga (Nyasa)", local: "chiTonga" },
  // {
  //   code3: "ton",
  //   code2: "to",
  //   name: "Tonga (Tonga Islands)",
  //   local: "Lea faka-Tonga",
  // },
  // { code3: "tpi", code2: "", name: "Tok Pisin", local: "Tok Pisin" },
  // { code3: "tsi", code2: "", name: "Tsimshian", local: "Sm'álgyax" },
  // { code3: "tsn", code2: "tn", name: "Tswana", local: "Setswana" },
  // { code3: "tso", code2: "ts", name: "Tsonga", local: "Xitsonga" },
  // { code3: "tuk", code2: "tk", name: "Turkmen", local: "Türkmençe" },
  // { code3: "tum", code2: "", name: "Tumbuka", local: "chiTumbuka" },
  // { code3: "tup", code2: "", name: "Tupi languages", local: "Tupi languages" },
  // { code3: "tur", code2: "tr", name: "Turkish", local: "Türkçe" },
  // {
  //   code3: "tut",
  //   code2: "",
  //   name: "Altaic languages",
  //   local: "Altaic languages",
  // },
  // { code3: "tvl", code2: "", name: "Tuvalu", local: "Te Ggana Tuuvalu" },
  // { code3: "twi", code2: "tw", name: "Twi", local: "Twi" },
  // { code3: "tyv", code2: "", name: "Tuvinian", local: "Тыва дыл" },
  // { code3: "udm", code2: "", name: "Udmurt", local: "Удмурт кыл" },
  // { code3: "uga", code2: "", name: "Ugaritic", local: "𐎀𐎂𐎗𐎚" },
  // { code3: "uig", code2: "ug", name: "Uighur; Uyghur", local: "ئۇيغۇرچە" },
  // { code3: "ukr", code2: "uk", name: "Ukrainian", local: "Українська" },
  // { code3: "umb", code2: "", name: "Umbundu", local: "Úmbúndú" },
  // { code3: "und", code2: "", name: "Undetermined", local: "Undetermined" },
  // { code3: "urd", code2: "ur", name: "Urdu", local: "اردو" },
  // { code3: "uzb", code2: "uz", name: "Uzbek", local: "Oʻzbekcha" },
  // { code3: "vai", code2: "", name: "Vai", local: "ꕙꔤ" },
  // { code3: "ven", code2: "ve", name: "Venda", local: "Tshivenḓa" },
  { code3: "vie", code2: "vi", name: "Vietnamese", local: "Tiếng Việt" },
  // { code3: "vol", code2: "vo", name: "Volapük", local: "Volapük" },
  // { code3: "vot", code2: "", name: "Votic", local: "Vađđa" },
  // {
  //   code3: "wak",
  //   code2: "",
  //   name: "Wakashan languages",
  //   local: "Wakashan languages",
  // },
  // { code3: "wal", code2: "", name: "Wolaitta; Wolaytta", local: "Wolaytta" },
  // { code3: "war", code2: "", name: "Waray", local: "Winaray" },
  // { code3: "was", code2: "", name: "Washo", local: "Wá:šiw" },
  // { code3: "wel", code2: "cy", name: "Welsh", local: "Cymraeg" },
  // {
  //   code3: "wen",
  //   code2: "",
  //   name: "Sorbian languages",
  //   local: "Sorbian languages",
  // },
  // { code3: "wln", code2: "wa", name: "Walloon", local: "Walon" },
  // { code3: "wol", code2: "wo", name: "Wolof", local: "Wolof" },
  // { code3: "xal", code2: "", name: "Kalmyk; Oirat", local: "Хальмг келн" },
  // { code3: "xho", code2: "xh", name: "Xhosa", local: "isiXhosa" },
  // { code3: "yao", code2: "", name: "Yao", local: "Chiyao" },
  // { code3: "yap", code2: "", name: "Yapese", local: "Yapese" },
  // { code3: "yid", code2: "yi", name: "Yiddish", local: "ייִדיש" },
  // { code3: "yor", code2: "yo", name: "Yoruba", local: "Yorùbá" },
  // {
  //   code3: "ypk",
  //   code2: "",
  //   name: "Yupik languages",
  //   local: "Yupik languages",
  // },
  // { code3: "zap", code2: "", name: "Zapotec", local: "Diidxazá" },
  // {
  //   code3: "zbl",
  //   code2: "",
  //   name: "Blissymbols; Blissymbolics; Bliss",
  //   local: "Blissymbols",
  // },
  // { code3: "zen", code2: "", name: "Zenaga", local: "Tuḍḍungiyya" },
  // {
  //   code3: "zgh",
  //   code2: "",
  //   name: "Standard Moroccan Tamazight",
  //   local: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
  // },
  // { code3: "zha", code2: "za", name: "Zhuang; Chuang", local: "Vahcuengh" },
  // { code3: "zho", code2: "zh", name: "Chinese", local: "中文" },
  // { code3: "znd", code2: "", name: "Zande languages", local: "Pazande" },
  // { code3: "zul", code2: "zu", name: "Zulu", local: "isiZulu" },
  // { code3: "zun", code2: "", name: "Zuni", local: "Shiwi'ma" },
  // {
  //   code3: "zza",
  //   code2: "",
  //   name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
  //   local: "Zazaki",
  // },
];

export const LANGUAGES_MAP_CODE2 = Object.fromEntries(
  LANGUAGES.map((lang) => [lang.code2, lang])
);

export const LANGUAGES_MAP_CODE3 = Object.fromEntries(
  LANGUAGES.map((lang) => [lang.code3, lang])
);
// some additional manual mappings (not clear if these should be in the "official" mappings)
if (LANGUAGES_MAP_CODE2.fa) {
  LANGUAGES_MAP_CODE3.pes = LANGUAGES_MAP_CODE2.fa;
}
