/**
 * List of screen's name
 */

//Auth navigation
export const NAVIGATION_AUTH_NAVIGATION = "NAVIGATION_AUTH_NAVIGATION";
export const NAVIGATION_LOGIN_SCREEN = "NAVIGATION_LOGIN_SCREEN";
export const NAVIGATION_REGISTER_ACCOUNT_SCREEN =
  "NAVIGATION_REGISTER_ACCOUNT_SCREEN";

//Main navigation
export const NAVIGATION_MAIN_NAVIGATION = "NAVIGATION_MAIN_NAVIGATION";
export const NAVIGATION_WELCOME_SCREEN = "NAVIGATION_WELCOME_SCREEN";
export const NAVIGATION_DETAIL_PRODUCT_SCREEN =
  "NAVIGATION_DETAIL_PRODUCT_SCREEN";
export const NAVIGATION_LIST_NOTIFICATIONS_SCREEN =
  "NAVIGATION_LIST_NOTIFICATIONS_SCREEN";
export const NAVIGATION_LIST_RIDE_SCREEN = "NAVIGATION_LIST_RIDE_SCREEN";
export const NAVIGATION_DETAIL_RIDE_SCREEN = "NAVIGATION_DETAIL_RIDE_SCREEN";
export const NAVIGATION_STATISTIC_RIDE_SCREEN =
  "NAVIGATION_STATISTIC_RIDE_SCREEN";
export const NAVIGATION_LOGS_DETAIL_SCREEN = "NAVIGATION_LOGS_DETAIL_SCREEN";
export const NAVIGATION_WEB_VIEW_SCREEN = "NAVIGATION_WEB_VIEW_SCREEN";
export const NAVIGATION_SETTINGS_SCREEN = "NAVIGATION_SETTINGS_SCREEN";
export const NAVIGATION_INTRODUCTION_BASE_SCREEN =
  "NAVIGATION_INTRODUCTION_BASE_SCREEN";
export const NAVIGATION_INTRODUCTION_OPTIMIZE_BASE_SCREEN =
  "NAVIGATION_INTRODUCTION_OPTIMIZE_BASE_SCREEN";
export const NAVIGATION_INTRODUCTION_FLASHLIST_SCREEN =
  "NAVIGATION_INTRODUCTION_FLASHLIST_SCREEN";
export const NAVIGATION_INTRODUCTION_FLASHLIST_OPTIMIZE_SCREEN =
  "NAVIGATION_INTRODUCTION_FLASHLIST_OPTIMIZE_SCREEN";
export const NAVIGATION_SETTINGS_LANGUAGE_SCREEN =
  "NAVIGATION_SETTINGS_LANGUAGE_SCREEN";

//Tab navigation
export const NAVIGATION_TAB_NAVIGATION = "NAVIGATION_TAB_NAVIGATION";
export const NAVIGATION_INTRODUCTION_SCREEN = "NAVIGATION_INTRODUCTION_SCREEN";
export const NAVIGATION_DOG_SCREEN = "NAVIGATION_DOG_SCREEN";
