/**
 * List of screen's name
 */

//Auth navigation
export const NAVIGATION_AUTH_NAVIGATION = "NAVIGATION_AUTH_NAVIGATION";
export const NAVIGATION_LOGIN_SCREEN = "NAVIGATION_LOGIN_SCREEN";
export const NAVIGATION_ONBOARDING_SCREEN = "NAVIGATION_ONBOARDING_SCREEN";

//Tab navigation
export const NAVIGATION_TAB_NAVIGATION = "NAVIGATION_TAB_NAVIGATION";
export const NAVIGATION_INTRODUCTION_SCREEN = "NAVIGATION_INTRODUCTION_SCREEN";
export const NAVIGATION_ABOUT_US_SCREEN = "NAVIGATION_ABOUT_US_SCREEN";

//Main navigation
export const NAVIGATION_MAIN_NAVIGATION = "NAVIGATION_MAIN_NAVIGATION";
export const NAVIGATION_DETAIL_PRODUCT_SCREEN =
  "NAVIGATION_DETAIL_PRODUCT_SCREEN";
export const NAVIGATION_SETTINGS_SCREEN = "NAVIGATION_SETTINGS_SCREEN";
export const NAVIGATION_INTRODUCTION_BASE_SCREEN =
  "NAVIGATION_INTRODUCTION_BASE_SCREEN";
export const NAVIGATION_INTRODUCTION_FLASHLIST_SCREEN =
  "NAVIGATION_INTRODUCTION_FLASHLIST_SCREEN";
export const NAVIGATION_SETTINGS_LANGUAGE_SCREEN =
  "NAVIGATION_SETTINGS_LANGUAGE_SCREEN";
export const NAVIGATION_DOG_SCREEN = "NAVIGATION_DOG_SCREEN";
export const NAVIGATION_STYLE_NATIVE_SCREEN = "NAVIGATION_STYLE_NATIVE_SCREEN";
export const NAVIGATION_STYLE_RESTYLE_SCREEN =
  "NAVIGATION_STYLE_RESTYLE_SCREEN";
